# Generated by Django 4.2 on 2024-09-27 03:04

from django.db import migrations, models
import savepost.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('key', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('views', models.IntegerField(default=0)),
                ('del_date', models.DateField(validators=[savepost.validators.date_validator])),
                ('last_query', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
