# Generated by Django 4.2 on 2024-07-21 20:21

from django.db import migrations, models
import savepost.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostUrls',
            fields=[
                ('key', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('file_url', models.URLField()),
                ('views', models.IntegerField(default=0)),
                ('del_date', models.DateField(validators=[savepost.validators.date_validator])),
            ],
        ),
    ]
