# Generated by Django 4.2 on 2024-08-14 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savepost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posturls',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 15, 30, 23, 354276, tzinfo=datetime.timezone.utc)),
        ),
    ]
