# Generated by Django 4.2 on 2024-10-10 16:32

from django.db import migrations, models
import post.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('key', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='название файла в хранилище S3')),
                ('views_count', models.IntegerField(default=0, verbose_name='счетчик просмотров')),
                ('delete_date', models.DateField(validators=[post.validators.post_date_validator], verbose_name='дата удаления поста')),
                ('last_query', models.DateTimeField(auto_now=True, verbose_name='время последнего запроса')),
            ],
        ),
    ]
